# Generated by Django 4.0.5 on 2022-06-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_persona_remove_producto_imagenprod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
