# Generated by Django 4.0.5 on 2022-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_persona_producto_imagenprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('idFundacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Fundacion')),
                ('nomFundacion', models.CharField(max_length=50, verbose_name='Nombre Fundacion')),
                ('dFundacion', models.CharField(max_length=50, verbose_name='Direccion Fundacion')),
                ('emailFundacion', models.CharField(max_length=50, verbose_name='Email Fundacion')),
                ('telfundacion', models.CharField(max_length=10, verbose_name=' Telefono fundacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagenProd',
        ),
    ]
