# Generated by Django 4.0.5 on 2022-06-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fundacion_remove_producto_imagenprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFundacion',
            fields=[
                ('idTipocat', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria Proucto')),
                ('nomCat', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='telfundacion',
            field=models.CharField(max_length=15, verbose_name='Telefono fundacion'),
        ),
    ]
