# Generated by Django 4.0.5 on 2022-06-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tipofundacion_alter_fundacion_telfundacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='core/static/img'),
        ),
    ]
