# Generated by Django 4.0.4 on 2022-07-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_fundacion_imgfundacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='formD',
            fields=[
                ('codFormuD', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Formulario')),
                ('nombreD', models.CharField(max_length=50, verbose_name='Nombre ')),
                ('apellidoD', models.CharField(max_length=50, verbose_name='Apellido')),
                ('mailD', models.EmailField(max_length=254, verbose_name='Correo')),
                ('rutD', models.IntegerField(verbose_name='Teléfono')),
                ('digito', models.CharField(max_length=1, verbose_name='digito')),
                ('direccionD', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('tipoCuenta', models.IntegerField(choices=[[1, 'cuenta vista'], [2, 'cuenta corriente']], verbose_name='Tipo cuenta')),
                ('banco', models.IntegerField(choices=[[1, 'Banco Estado'], [2, 'Banco Chile'], [3, 'Banco Falabella'], [4, 'Banco Itau'], [5, 'Banco Scotiebank'], [6, 'Banco Santander'], [7, 'Banco BCI']], verbose_name='Banco')),
                ('fundacion', models.IntegerField(choices=[[1, 'Callejeros buscan hogar'], [2, 'Fundación Julieta'], [3, 'Garras & patas'], [4, 'Fundación Julieta']], verbose_name='Nombre de la fundación')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('codUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Rut sin digito sin guión')),
                ('nombreUsuario', models.CharField(max_length=20, verbose_name='Nombre')),
                ('password', models.CharField(max_length=20, verbose_name='clave')),
                ('estadoU', models.IntegerField(verbose_name='Estado usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='comunaF',
            field=models.CharField(blank=True, max_length=250, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='regionF',
            field=models.CharField(blank=True, max_length=250, verbose_name='Región de Cliente'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='codFundacion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Fundación'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='descFundacion',
            field=models.CharField(max_length=200, verbose_name='Descripción Fundación'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='dirFundacion',
            field=models.CharField(max_length=50, verbose_name='Dirección Fundación'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='nomFundacion',
            field=models.CharField(max_length=50, verbose_name='Nombre Fundación'),
        ),
        migrations.AlterField(
            model_name='fundacion',
            name='telFundacion',
            field=models.IntegerField(verbose_name='Teléfono Contacto'),
        ),
    ]
