# Generated by Django 4.0.5 on 2022-06-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contacto_regionf'),
        ('core', '0015_remove_producto_imagenprod'),
    ]

    operations = [
    ]
