# Generated by Django 4.0.4 on 2022-07-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_formd_usuario_alter_contacto_comunaf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoPedido',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='código')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPromo', models.IntegerField(verbose_name='Código promoción')),
                ('descripcionP', models.CharField(max_length=20, verbose_name='Descripción')),
                ('descuento', models.IntegerField(verbose_name='descuento')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('codPedido', models.AutoField(primary_key=True, serialize=False, verbose_name='Código compra')),
                ('fechaPedido', models.DateField(verbose_name='Fecha Compra')),
                ('fechaPago', models.DateField(verbose_name='Fecha pago')),
                ('tipoPedido', models.IntegerField(verbose_name='Tipo de compra')),
                ('codFactura', models.IntegerField(verbose_name='Código factura')),
                ('totalPedido', models.IntegerField(verbose_name='Total')),
                ('estadoPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadopedido')),
            ],
        ),
    ]
