# Generated by Django 4.0.5 on 2022-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20220616_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fundacion',
        ),
        migrations.DeleteModel(
            name='TipoFundacion',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mailF',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='regionF',
            field=models.CharField(max_length=250, verbose_name='Región de Cliente'),
        ),
    ]
