# Generated by Django 4.0.4 on 2022-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_estadopedido_promo_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre producto')),
                ('precio', models.IntegerField(verbose_name='Precio Producto')),
            ],
        ),
        migrations.AlterField(
            model_name='formd',
            name='rutD',
            field=models.IntegerField(verbose_name='Rut'),
        ),
    ]
