# Generated by Django 4.0.4 on 2022-07-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_carrito_alter_formd_rutd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
