# Generated by Django 4.0.5 on 2022-06-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_fundacion_imgfundacion_and_more'),
        ('core', '0017_delete_fundacion_delete_tipofundacion_and_more'),
    ]

    operations = [
    ]
