# Generated by Django 4.0.4 on 2022-07-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codUser', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido ')),
                ('mailUser', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.IntegerField(verbose_name='Telefono User')),
                ('nombreUser', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('passUser', models.CharField(max_length=50, verbose_name='Contraseña Usuario')),
            ],
        ),
    ]
