# Generated by Django 4.0.4 on 2022-07-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='codFormu',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Formulario'),
        ),
    ]
