# Generated by Django 4.0.4 on 2022-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_contacto_codformu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carrito',
        ),
        migrations.AlterField(
            model_name='producto',
            name='codProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripcción Producto'),
        ),
    ]
